FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements-generator.txt .

RUN pip install --no-cache-dir -r requirements-generator.txt

CMD ["python", "generate_data.py"]
