
# Name your project! Project names should be lowercase and underscored
name: 'oms_realtime_analytics'
version: '1.0.0'
config-version: 2

profile: 'oms_realtime_analytics'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  oms_realtime_analytics:
    staging:
      materialized: view
      schema: staging
    marts:
      materialized: table
      schema: marts

vars:
  start_date: '2024-01-01'
  
on-run-start: []
on-run-end: []
