oms_realtime_analytics:
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5434
      user: analyst
      password: analyst_pass
      dbname: analytics
      schema: public
      threads: 4
      keepalives_idle: 0
      
    prod:
      type: postgres
      host: warehouse-db
      port: 5432
      user: analyst
      password: analyst_pass
      dbname: analytics
      schema: public
      threads: 4
      keepalives_idle: 0
      
  target: dev
