oms_realtime_analytics:
  outputs:
    dev:
      type: doris
      host: localhost
      port: 9030
      user: root
      password: ''
      database: ecom
      schema: ecom
      threads: 4
      driver: 'mysql'
      
    prod:
      type: doris
      host: doris-fe
      port: 9030
      user: root
      password: ''
      database: ecom
      schema: ecom
      threads: 4
      driver: 'mysql'
      
  target: dev
